### ISSUE TITLE
Please provide text of the theme

### ISSUE THREAD

**Issue by wsmelton** [edurojasr/Windows_Terminal_Theme_Night_Owl#1]
Providing a screen image of the theme is time consuming for users to re-type. It would be more user-friendly if a text version of the dark and light theme were included either in the readme, or as individual files.

**Comment by edurojasr** [comment]
Hi Shawn!

They are in the schemes.json file in the root directory!

**Comment by wsmelton** [comment]
Might add that as a note....just to cover those of that don't look at the file list and just the readme 😁

**Comment by edurojasr** [comment]
of course I'm going to do it 👍 

thanks for the suggestion!
