### ISSUE TITLE
Applied the theme, but color scheme is still default. 

### ISSUE THREAD

**Issue by Re-fresh** [edurojasr/Windows_Terminal_Theme_Night_Owl#2]
Text colors are default as original even after applying the theme. Only the background changed and rest all is the same.

![image](https://user-images.githubusercontent.com/59319728/86742344-adde4680-c055-11ea-8d51-6a144656758a.png)

**Comment by edurojasr** [comment]
Hi!

Could you use this function in powershell to check the colors?

`
$colors = [enum]::GetValues([System.ConsoleColor])
Foreach ($bgcolor in $colors){
    Foreach ($fgcolor in $colors) { Write-Host "$fgcolor|"  -ForegroundColor $fgcolor -BackgroundColor $bgcolor -NoNewLine }
    Write-Host " on $bgcolor"
}
`
Or if you use Bash on WSL2 

`sudo apt-get install colortest`

`colortest-16b`

Let me show you the difference with the default powershell theme:

This is the defaul powershell terminal theme
![default](https://user-images.githubusercontent.com/35645729/86807215-e91d4d00-c036-11ea-9c28-29428ff78379.png)

This is the terminal with this theme
![night-owl](https://user-images.githubusercontent.com/35645729/86807327-fdf9e080-c036-11ea-8454-4d019092a025.png)

As you can see, they are similar but the Night-Owl uses a little more pastel color scheme

I intend to give more work to this adaptation, to be able to better replicate the theme

**Comment by Re-fresh** [comment]
Yeah, sorry for the trouble. I'm assumed something else, my bad, everythings seems to work fine.
