### ISSUE TITLE
Missing digit on light theme

### ISSUE THREAD

**Issue by GusPrado** [edurojasr/Windows_Terminal_Theme_Night_Owl#5]
Hi there!

There is a missing digit on brightYellow to form RGB pattern for the light theme that causes an error when you try to save this color scheme. I suppose it's a '1' that makes "#DAA011"  once it culminates in a yellow shape.

Hope that helps with fixing it.

**Comment by edurojasr** [comment]
Thanks @GusPrado!

I'm going to fix it today later 😃
